name: Main workflow

on:
  pull_request:
  push:

jobs:
  windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set-up OCaml
        uses: ocaml/setup-ocaml@v2
        with:
          opam-pin: false
          opam-depext: false
          ocaml-compiler: ocaml.5.0.0,ocaml-option-mingw
          opam-repositories: |
            dra27: https://github.com/dra27/opam-repository.git#windows-5.0
            duniverse: git+https://github.com/dune-universe/opam-overlays
            normal: https://github.com/ocaml/opam-repository.git
            default: https://github.com/ocaml-opam/opam-repository-mingw.git#opam2
      # --with-version=dev is not available, and --with-test also tries running tests for packages (like MDX) which fail...
      - run: | 
          echo "OPAMCLI=2.1" >>"$GITHUB_ENV"
          opam pin -yn eio.dev .
          opam pin -yn eio_windows.dev .
          opam install ocamlfind.1.9.5 kcas alcotest mdx crowbar -y
          opam install eio eio_windows --deps-only
      - run: opam exec -- dune build @runtest
      - run: dune exec -- ./examples/net/main.exe
